version: '3.1'
services:
  # mongo:
  #   image: mongo:bionic
  #   container_name: mongo
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: giftrAdmin
  #     MONGO_INITDB_ROOT_PASSWORD: NIpNIPsR7BnVkcpd
  #   ports:
  #     - 27017:27017
  #   restart: always
  #   volumes:
  #     - ./data/mongo:/data/db

  express:
    image: giftr-api-w21
    container_name: giftr-api-w21
    # depends_on:
    #   - mongo
    environment:
      API_JWTKEY: xzk12x7ag6vyph380o4hwa89yc1f55
      API_APIKEY: dudh0004
      API_PORT: 80
      NODE_ENV: 'stage'
    ports:
      - 3030:80
    command: node server.js
